// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpjIbVtqEhTANOZAFXmSXt3DcOms6V6Q',
    appId: '1:1062155543768:web:2c6754667177ee65f3e3ad',
    messagingSenderId: '1062155543768',
    projectId: 'flutter-dart-firstapp',
    authDomain: 'flutter-dart-firstapp.firebaseapp.com',
    storageBucket: 'flutter-dart-firstapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI0Fxe07ZkfZ31D0ReNRrmKmsnWJNyzLo',
    appId: '1:1062155543768:android:60ac003d38117728f3e3ad',
    messagingSenderId: '1062155543768',
    projectId: 'flutter-dart-firstapp',
    storageBucket: 'flutter-dart-firstapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8qFm5TCrG0jCFMvDnG5Lh2usHHH7pRik',
    appId: '1:1062155543768:ios:2e0193b6d2ccddcff3e3ad',
    messagingSenderId: '1062155543768',
    projectId: 'flutter-dart-firstapp',
    storageBucket: 'flutter-dart-firstapp.appspot.com',
    iosBundleId: 'com.fabian.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8qFm5TCrG0jCFMvDnG5Lh2usHHH7pRik',
    appId: '1:1062155543768:ios:7cb83b98eea284d8f3e3ad',
    messagingSenderId: '1062155543768',
    projectId: 'flutter-dart-firstapp',
    storageBucket: 'flutter-dart-firstapp.appspot.com',
    iosBundleId: 'com.fabian.firstapp.RunnerTests',
  );
}
